import type { ImageSourcePropType } from "react-native";

export const exerciseIconSources = {
  "pompes": require("../../exos-icons/01-pompes.png"),
  "squats": require("../../exos-icons/02-squats.png"),
  "fentes": require("../../exos-icons/03-fentes.png"),
  "gainage-planche": require("../../exos-icons/04-gainage-planche.png"),
  "gainage-lateral": require("../../exos-icons/05-gainage-lateral.png"),
  "mountain-climbers": require("../../exos-icons/06-mountain-climbers.png"),
  "burpees": require("../../exos-icons/07-burpees.png"),
  "jumping-jacks": require("../../exos-icons/08-jumping-jacks.png"),
  "tractions": require("../../exos-icons/09-tractions.png"),
  "dips": require("../../exos-icons/10-dips.png"),
  "pompes-inclinees": require("../../exos-icons/11-pompes-inclinees.png"),
  "pompes-declinees": require("../../exos-icons/12-pompes-declinees.png"),
  "pike-push-ups": require("../../exos-icons/13-pike-push-ups.png"),
  "hollow-hold": require("../../exos-icons/14-hollow-hold.png"),
  "superman": require("../../exos-icons/15-superman.png"),
  "pont-fessier": require("../../exos-icons/16-pont-fessier.png"),
  "pistol-squat": require("../../exos-icons/17-pistol-squat.png"),
  "chaise-murale": require("../../exos-icons/18-chaise-murale.png"),
  "montees-sur-pointes": require("../../exos-icons/19-montees-sur-pointes.png"),
  "step-up": require("../../exos-icons/20-step-up.png"),
  "sauts-sur-box": require("../../exos-icons/21-sauts-sur-box.png"),
  "sauts-squat": require("../../exos-icons/22-sauts-squat.png"),
  "sauts-groupes": require("../../exos-icons/23-sauts-groupes.png"),
  "montees-de-genoux": require("../../exos-icons/24-montees-de-genoux.png"),
  "leve-de-jambes": require("../../exos-icons/25-leve-de-jambes.png"),
  "leve-de-genoux-suspendu": require("../../exos-icons/26-leve-de-genoux-suspendu.png"),
  "battements-de-jambes": require("../../exos-icons/27-battements-de-jambes.png"),
  "abdos-bicyclette": require("../../exos-icons/28-abdos-bicyclette.png"),
  "crunchs": require("../../exos-icons/29-crunchs.png"),
  "crunchs-inverses": require("../../exos-icons/30-crunchs-inverses.png"),
  "gainage-tap-epaules": require("../../exos-icons/31-gainage-tap-epaules.png"),
  "bear-crawl": require("../../exos-icons/32-bear-crawl.png"),
  "crab-walk": require("../../exos-icons/33-crab-walk.png"),
  "inchworm": require("../../exos-icons/34-inchworm.png"),
  "down-dog": require("../../exos-icons/35-down-dog.png"),
  "cobra": require("../../exos-icons/36-cobra.png"),
  "planche-vers-pompe": require("../../exos-icons/37-planche-vers-pompe.png"),
  "gainage-lateral-avec-crunch": require("../../exos-icons/38-gainage-lateral-avec-crunch.png"),
  "handstand-au-mur": require("../../exos-icons/39-handstand-au-mur.png"),
  "squat-pulse": require("../../exos-icons/40-squat-pulse.png"),
  "running-marche-lente": require("../../exos-icons/running/01-marche-lente.png"),
  "running-marche-rapide": require("../../exos-icons/running/02-marche-rapide.png"),
  "running-footing-leger": require("../../exos-icons/running/03-footing-leger.png"),
  "running-jogging-recuperation": require("../../exos-icons/running/04-jogging-recuperation.png"),
  "running-respiration-controlee": require("../../exos-icons/running/05-respiration-controlee.png"),
  "running-course-moderee": require("../../exos-icons/running/06-course-moderee.png"),
  "running-tempo-run": require("../../exos-icons/running/07-tempo-run.png"),
  "running-progressif": require("../../exos-icons/running/08-progressif.png"),
  "running-fartlek": require("../../exos-icons/running/09-fartlek.png"),
  "running-montee-douce": require("../../exos-icons/running/10-montee-douce.png"),
  "running-sprint": require("../../exos-icons/running/11-sprint.png"),
  "running-acceleration-progressive": require("../../exos-icons/running/12-acceleration-progressive.png"),
  "running-intervalles-rapides": require("../../exos-icons/running/13-intervalles-rapides.png"),
  "running-sprints-en-cote": require("../../exos-icons/running/14-sprints-en-cote.png"),
  "running-relances": require("../../exos-icons/running/15-relances.png"),
  "running-montees-de-genoux": require("../../exos-icons/running/16-montees-de-genoux.png"),
  "running-talons-fesses": require("../../exos-icons/running/17-talons-fesses.png"),
  "running-pas-chasses": require("../../exos-icons/running/18-pas-chasses.png"),
  "running-skipping": require("../../exos-icons/running/19-skipping.png"),
  "running-course-jambes-tendues": require("../../exos-icons/running/20-course-jambes-tendues.png"),
  "running-bondissements": require("../../exos-icons/running/21-bondissements.png"),
  "running-fentes-marchees": require("../../exos-icons/running/22-fentes-marchees.png"),
  "running-squats-dynamiques": require("../../exos-icons/running/23-squats-dynamiques.png"),
  "running-gainage-dynamique": require("../../exos-icons/running/24-gainage-dynamique.png"),
  "running-pas-de-l-ours": require("../../exos-icons/running/25-pas-de-l-ours.png"),
  "running-montee-de-genoux-lente": require("../../exos-icons/running/26-montee-de-genoux-lente.png"),
  "running-recuperation-active": require("../../exos-icons/running/27-recuperation-active.png"),
  "running-course-en-respiration-controlee": require("../../exos-icons/running/28-course-en-respiration-controlee.png"),
  "running-run-tempo-soutenu": require("../../exos-icons/running/29-run-tempo-soutenu.png"),
  "running-footing-progressif": require("../../exos-icons/running/30-footing-progressif.png"),
  "running-course-en-cote": require("../../exos-icons/running/31-course-en-cote.png"),
  "running-course-en-descente": require("../../exos-icons/running/32-course-en-descente.png"),
  "running-petits-pas-rapides": require("../../exos-icons/running/33-petits-pas-rapides.png"),
  "running-course-arriere": require("../../exos-icons/running/34-course-arriere.png"),
  "running-ouverture-de-foulee": require("../../exos-icons/running/35-ouverture-de-foulee.png"),
  "running-sprints-lateraux": require("../../exos-icons/running/36-sprints-lateraux.png"),
  "running-pas-croises": require("../../exos-icons/running/37-pas-croises.png"),
  "running-foulees-bondissantes": require("../../exos-icons/running/38-foulees-bondissantes.png"),
  "running-acceleration-finale": require("../../exos-icons/running/39-acceleration-finale.png"),
  "running-retour-au-calme": require("../../exos-icons/running/40-retour-au-calme.png"),
} as const satisfies Record<string, ImageSourcePropType>;

export type ExerciseIconId = keyof typeof exerciseIconSources;

export function getExerciseIconSource(iconId: string): ImageSourcePropType | undefined {
  return exerciseIconSources[iconId as ExerciseIconId];
}
